package constants.cards

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val CARD_ELEVATION = 10.dp

val OPTION_CARD_HEIGHT = 40.dp
val OPTION_CARD_PADDING_END = 10.dp
val OPTION_CARD_TEXT_FONT_SIZE = 18.sp
val OPTION_CARD_TEXT_PADDING_START = 15.dp
val OPTION_CARD_TEXT_PADDING_END = 15.dp
val OPTION_CARD_ICON_PADDING_END = 5.dp

val RECIPE_CARD_HEIGHT = 290.dp
val RECIPE_CARD_WIDTH = 250.dp
val RECIPE_CARD_PADDING_END = 10.dp

val SEE_ALL_CARD_HEIGHT = 100.dp
val SEE_ALL_CARD_PADDING_END = 10.dp
val SEE_ALL_CARD_PADDING_BOTTOM = 10.dp

val VERTICAL_RECIPE_CARD_IMAGE_HEIGHT = 200.dp
val V_RECIPE_CARD_IMAGE_PADDING_TOP = 10.dp
val V_RECIPE_CARD_IMAGE_PADDING_BOTTOM = 10.dp
val V_RECIPE_CARD_CONTENT_PADDING_START = 15.dp
val V_RECIPE_CARD_CONTENT_PADDING_BOTTOM = 5.dp
val V_RECIPE_CARD_CONTENT_PADDING_END = 10.dp
val V_RECIPE_CARD_RATING_BOX_HEIGHT = 40.dp
val V_RECIPE_CARD_RATING_BOX_PADDING_START = 5.dp
val V_RECIPE_CARD_RATING_BOX_PADDING_END = 5.dp

const val MAX_RECENT_RECIPE_COUNT = 7
