package constants.cards

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

val CARD_ELEVATION = 10.dp

val OPTION_CARD_HEIGHT = 40.dp
val OPTION_CARD_PADDING_END = 10.dp
val OPTION_CARD_TEXT_FONT_SIZE = 18.sp
val OPTION_CARD_TEXT_PADDING_START = 15.dp
val OPTION_CARD_TEXT_PADDING_END = 15.dp

val RECIPE_CARD_HEIGHT = 250.dp
val RECIPE_CARD_WIDTH = 250.dp
val RECIPE_CARD_PADDING_END = 10.dp
val RECIPE_CARD_TEXT_FONT_SIZE = 18.sp
val RECIPE_CARD_TEXT_PADDING_START = 15.dp
val RECIPE_CARD_TEXT_PADDING_END = 15.dp